version: 2
jobs:
  build-test:
    macos:
      xcode: "11.1.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - gem-cache-
      - run:
          bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bin/bootstrap-if-needed
      - run:
          name: Run Unit Tests
          command: bundle exec fastlane unit_tests
          environment:
            SCAN_DEVICE: iPhone 5s
            SCAN_SCHEME: WebTests
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test