version: 2
jobs:
  dependencies:
    macos:
      xcode: "11.1.0"
    working_directory: /Users/distiller/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - gem-cache-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: mv Cartfile.resolved Carthage
      - restore_cache:
          keys:
            - carthage-cache-{{ checksum "Cartfile.resolved" }}
            - carthage-cache-
      - run: bin/bootstrap-if-needed
      - save_cache:
          key: carthage-cache-{{ checksum "Cartfile.resolved" }}
          paths:
            - Carthage
  unit_tests:
    macos:
      xcode: "11.1.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - gem-cache-
      - run: bundle install --path vendor/bundle
      - restore_cache:
          keys:
            - carthage-cache-{{ checksum "Cartfile.resolved" }}
            - carthage-cache-
      - run:
          name: Run Unit Tests
          command: bundle exec fastlane unit_tests
          environment:
            SCAN_DEVICE: iPhone 5s
            SCAN_SCHEME: WebTests
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
  ui_tests:
    macos:
      xcode: "11.1.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - gem-cache-
      - run: bundle install --path vendor/bundle
      - restore_cache:
          keys:
            - carthage-cache-{{ checksum "Cartfile.resolved" }}
            - carthage-cache-
      - run:
          name: Run UI Tests
          command: bundle exec fastlane ui_tests
          environment:
            SCAN_DEVICE: iPhone 5s
            SCAN_SCHEME: WebTests
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
  deploy:
    macos:
      xcode: "11.1.0"
    working_directory: /Users/distiller/project
    steps:
      - checkout
      - run: bundle exec fastlane beta
workflows:
  version: 2
  build-and-test:
    jobs:
      - dependencies
      - unit_tests:
          requires:
            - dependencies
      - ui_tests:
          requires:
            - dependencies
      - deploy:
          requires:
            - unit_tests
            - ui_tests