version: 2
jobs:
  build:
    macos:
      xcode: "11.1.0"
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: bundle install
      - run: bin/bootstrap-if-needed
      - run:
          name: Run Unit Tests
          command: bundle exec fastlane unit_tests
          environment:
            SCAN_DEVICE: iPhone 5s
            SCAN_SCHEME: WebTests
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs