default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc 'Runs Unit Test'
  lane :unit_tests do
    scan(
      project: 'Offers.xcodeproj',
      devices: ['iPhone 5s'],
      clean: true,
      scheme: 'OffersTests',
      code_coverage: true
    )
  end

  desc 'Runs UI Test'
  lane :ui_tests do
    scan(
      clean: true,
      devices: ['iPhone 5s'],
      project: 'Offers.xcodeproj',
      scheme: 'OffersUITests'
    )
  end

  desc 'Run all tests'
  lane :test do
    self.unit_tests
    self.ui_tests
  end

  desc 'Register devices'
  lane :sprout do
    register_devices(
      devices: {
        "Gideon's iPhone" => "245bc927a05d5d464130a93a747a185916222c98"
      },
      team_id: ENV["TEAM_ID"],
      username: ENV["APP_STORE_CONNECT_ID"]
    )
  end

  desc 'Deploy to TestFlight'
  lane :beta do
    ensure_git_status_clean
    increment_build_number
    build_number = get_build_number(
      xcodeproj: "Offers.xcodeproj"
    )
    commit_version_bump(
      message: "Build Number Bump [ci skip]: #{build_number}",
      xcodeproj: 'Offers.xcodeproj'
    )
    push_to_git_remote(
      remote: 'origin'
    )

    match(
      app_identifier: 'io.piofusco.offers',
      type: 'appstore'
    )

    build_app(
      export_method: 'app-store',
      output_directory: 'build',
      project: 'Offers.xcodeproj',
      scheme: 'Offers'
    )
    testflight(
      app_identifier: 'io.piofusco.offers',
      ipa: 'build/Offers.ipa',
      skip_waiting_for_build_processing: true,
      team_id: ENV['TEAM_ID'],
      username: ENV['APP_STORE_CONNECT_ID'],
    )
  end
end
