# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs Unit Test"
  lane :unit_tests do
    scan(
      project: "Offers.xcodeproj",
      devices: ["iPhone 5s"],
      clean: true,
      scheme: "OffersTests",
      code_coverage: true
    )
  end

  desc "Runs UI Test"
  lane :ui_tests do
    scan(
      project: "Offers.xcodeproj",
      devices: ["iPhone 5s"],
      clean: true,
      scheme: "OffersUITests"
    )
  end

  desc "Run all tests"
  lane :test do
    self.unit_tests
    self.ui_tests
  end
end
