# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc 'Runs Unit Test'
  lane :unit_tests do
    scan(
      project: 'Offers.xcodeproj',
      devices: ['iPhone 5s'],
      clean: true,
      scheme: 'OffersTests',
      code_coverage: true
    )
  end

  desc 'Runs UI Test'
  lane :ui_tests do
    scan(
      clean: true,
      devices: ['iPhone 5s'],
      project: 'Offers.xcodeproj',
      scheme: 'OffersUITests'
    )
  end

  desc 'Run all tests'
  lane :test do
    self.unit_tests
    self.ui_tests
  end

  desc 'Deploy to TestFlight'
  lane :beta do
    ensure_git_status_clean
    increment_build_number
    commit_version_bump(
      message: 'Version Bump',
      xcodeproj: 'Offers.xcodeproj'
    )
    push_to_git_remote(
      remote: 'origin'
    )

    match(
      app_identifier: ENV['APP_ID'],
      type: 'appstore'
    )

    build_app(
      export_method: 'app-store',
      output_directory: 'build',
      project: 'Offers.xcodeproj',
      scheme: 'Offers'
    )
    testflight(
      app_identifier: ENV['APP_ID'],
      ipa: 'build/Offers.ipa',
      skip_waiting_for_build_processing: true,
      team_id: ENV['TEAM_ID'],
      username: ENV['ITUNES_CONNECT_ID'],
    )
  end
end
